import { Inter } from "next/font/google";
import Head from 'next/head'
import BottomNav from "../components/BottomNav";
import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"],
  display: "swap"
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet"/>
        
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet"></link>
      </Head>

      <body className={inter.className}>
      <div className="overflow-contain">
          <BottomNav />
        </div>
        {children}
      </body>
    </html>
  );
}
