import { Inter } from "next/font/google";
import BottomNav from "../components/BottomNav";
import Footer from "../components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="overflow-contain">
          <BottomNav />
        </div>
        {children}
       <footer><Footer /></footer> 
      </body>
    </html>
  );
}
